name: interactive_shape_recognition
description: Dart port of inkandswitch/interactive-shape-recognition, an implementation of "A Simple Approach to Recognise Geometric Shapes Interactively".
version: 1.1.1
homepage: https://adil192.github.io/interactive_shape_recognition
repository: https://github.com/adil192/interactive_shape_recognition
issue_tracker: https://github.com/adil192/interactive_shape_recognition/issues

topics:
  - math
  - shape-recognition
  - polygons
  - js-port

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  convex_hull: ^1.1.2
  area_polygon: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
